version: "3.7"

services:
  mysql:
    image: mysql:8.0.27
    ports: 
      - 3037:3036
    environment:
      - MYSQL_ROOT_PASSWORD=rahasia
      - MYSQL_DATABASE=sinar-arco
    volumes:
      - ./server/docs/doc.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
  sinar-arco-backend:
    build: ./server
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rahasia
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=sinar-arco
    depends_on: 
      - mysql
      - redis